# Generated by Django 5.1.7 on 2025-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoiceupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
