# Generated by Django 5.1.7 on 2025-04-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoiceupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceupload',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
