# Generated by Django 5.1.6 on 2025-02-19 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_rename_recieved_date_email_received_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('invoice_lookup_link', models.URLField()),
                ('invoice_code', models.CharField(max_length=50)),
                ('template_number', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(max_length=50)),
                ('ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bl_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_vnd', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_usd', models.CharField(blank=True, max_length=100, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.email')),
            ],
        ),
    ]
