# Generated by Django 5.1.6 on 2025-02-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoicedata_invoice_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedata',
            name='bl_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='invoice_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='ref_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
