# Generated by Django 5.1.7 on 2025-04-27 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceupload',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='extractedinvoice',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted', to='invoices.invoiceupload'),
        ),
    ]
