# Generated by Django 5.1.7 on 2025-03-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedinvoice',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
