# Generated by Django 5.1.7 on 2025-04-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoiceupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files/'),
        ),
    ]
