# Generated by Django 5.1.7 on 2025-04-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_extractedinvoice_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceupload',
            name='file',
        ),
    ]
