# Generated by Django 5.1.7 on 2025-04-04 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_companyverification_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationdetail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='verificationresult',
            name='invoice',
        ),
        migrations.AddField(
            model_name='companyverification',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_verifications', to='invoices.extractedinvoice'),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='role',
            field=models.CharField(blank=True, choices=[('seller', 'Seller'), ('buyer', 'Buyer')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companyverification',
            name='message',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='InvoiceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=10)),
                ('result_content', models.TextField()),
                ('source', models.CharField(default='hoadondientu', max_length=50)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_verification', to='invoices.extractedinvoice')),
            ],
        ),
        migrations.DeleteModel(
            name='VerificationCategory',
        ),
        migrations.DeleteModel(
            name='VerificationDetail',
        ),
        migrations.DeleteModel(
            name='VerificationResult',
        ),
    ]
