# Generated by Django 5.1.7 on 2025-04-07 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_remove_verificationdetail_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=10)),
                ('match_content', models.BooleanField(default=False)),
                ('result_detail', models.TextField()),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_verification', to='invoices.extractedinvoice')),
            ],
        ),
    ]
