# Generated by Django 5.1.7 on 2025-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_signatureverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedinvoice',
            name='link_tra_cuu',
            field=models.URLField(blank=True, null=True),
        ),
    ]
