# Generated by Django 5.1.7 on 2025-04-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_extractedinvoice_link_tra_cuu'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedinvoice',
            name='ma_tra_cuu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
