# Generated by Django 5.1.7 on 2025-04-14 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_extractedinvoice_ma_tra_cuu'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedXMLInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('seller_tax_code', models.CharField(max_length=20)),
                ('buyer_tax_code', models.CharField(max_length=20)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('vat_amount', models.FloatField(blank=True, null=True)),
                ('grand_total', models.FloatField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoices.extractedinvoice')),
            ],
        ),
    ]
