# Generated by Django 5.1.7 on 2025-04-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_verifiedxmlinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedxmlinvoice',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verifiedxmlinvoice',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verifiedxmlinvoice',
            name='raw_xml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verifiedxmlinvoice',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
