# Generated by Django 5.1.7 on 2025-04-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_verifiedxmlinvoice_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedinvoice',
            name='xml_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
