# Generated by Django 5.1.7 on 2025-04-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_extractedinvoice_xml_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedxmlinvoice',
            name='local_xml_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
