# Generated by Django 5.1.7 on 2025-04-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_verifiedxmlinvoice_local_xml_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedinvoice',
            name='link_tra_cuu',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='extractedinvoice',
            name='xml_filename',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
